server:
  port: 9002

zeebe:
  client:
    worker:
      hazelcast:
        # 连接点，多个逗号分隔
        connection: localhost:5701,127.0.0.1:5701
        connectionTimeout: PT1M
        ringbuffer: zeebe
        connectionInitialBackoff: PT15S
        connectionBackoffMultiplier: 2.0
        connectionMaxBackoff: PT30S




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zeebedb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
